### ISSUE TITLE
Error in the "incidence_angle_tilted" function.

### ISSUE THREAD

**Issue by magipamies** [hectornieto/meteo_utils#1]
There is a problem in the "incidence_angle_tilted" function of the "dem_utils.py" script. Because it switches twice from degrees to radians.

Inside the function, it is converted from degrees to radians:

```
# aspect is considered the azimuth from the South being westward positive
    lat, aspect, slope = map(np.radians, [lat, aspect - 180, slope])
    f1, f2, f3 = inclination_factors(lat, slope, aspect)
```

but then the function "inclination_factors" is used in which it is also converted from degrees to radians:

```
def inclination_factors(lat, slope, aspect):
    # Convert remaining angles into radians,
    # aspect is considered the azimuth from the South being westward positive
    lat, aspect, slope = map(np.radians, [lat, aspect - 180, slope])
```

**Comment by hectornieto** [comment]
Thanks for spotting this bug :-)
